### PR TITLE
Replace preprocessor defined test/debug/run-modes by command line parameters

### PR DESCRIPTION
**Pull request by GrimSqueaker**
What I did:
- Replaced the preprocessor defines from sub_main by command line parameters.
- Implemented a class for command line parsing
- Implemented a unit test for this class
- Replaced occurances of the preprocessor switches in the code by feature flags provided by the new class
- Tried to keep the naming of the CLI params as close to the previously used defines as possible. (see CommandLineParser.cpp)

Why:
- This way it is possible to compile an executable once and use it to play, test regressions, etc.
- Before it was possible to introduce errors in code paths that are disabled by a define - this should not happen anymore.
- This is a preparation for being able to automate regression tests in the Github actions.
- The additional command line parser should not interfere with the original command line options.

Please check if the debug functionality still works, as I could not test all flags. I fear that merging in the latest development branch did break some regression test code. Before the merge the regression tests started via "remc2 --mode_test_regressions_game" kind of worked (finding differences) but now they seem to crash.

### CODE REVIEW

**Comment by GrimSqueaker** [comment]
Could you please add CommandLineParser.[h|cpp] to the VS solution?

**Comment by thobbsinteractive** [comment]
Amazing work buddy. This makes sense and is a boring but necessary task to implement so you have my admiration.

**Comment by turican0** [comment]
Thanks a lot, great job! As soon as it's merged, I'll take a look at it, if anything was wrong, I'll fix it. But I tested my dev version yesterday and except for level 22 it passed, so I don't see why it wouldn't work.

**Review by turican0 — APPROVED** [review]

**Comment by thobbsinteractive** [comment]
I just had a thought. Doesn't this mean the debug code is in the build no
matter what, even if it is not called? I am not sure if there are any
downsides to that, but we could tag all this just for debug?

Also do the games existing command line parameters still work? I assume
this code does not touch them from what I have seen.

**Comment by turican0** [comment]
For me the tests worked fine, if they fail maybe some variables behave specifically on different PCs and we will have to find them and fix them or put them in exceptions.

**Comment by turican0** [comment]
The fridge code doesn't matter, it is minimal due to the size of the code. From what I've seen, it shouldn't affect the standard parameters because they are named differently. I haven't tested it yet, maybe in time.
The special parameters might be named differently, but I'd leave it for now, as it's still changing, at least until I finish the network.
Anyway, it's a cool move, even I was complicating my job commenting out the options before translation.

**Comment by GrimSqueaker** [comment]
That the debug code is in there should not really matter. I also do not expect any performance impact as modern cpus with branch prediction are not really impacted by some if conditions.
I think it would make sense to clean up the flags a little.
Also a limitation at the moment is that it only can handle flags. It might make sense to pass in some integers or filenames and paths. I also thought of using a library for this which would bring a lot more features for free, but decided that it might be better to not to introduce another dependency.

**Comment by GrimSqueaker** [comment]
One more thing: As there is a functioning unit test available now, I think that I will take a look at the Linux Github action and enable UTs for our PR builds.
Maybe you can also set this up on local Windows builds. I think Visual Studio works nicely with GoogleTest but I never had had hands-on experience with that.

**Comment by thobbsinteractive** [comment]
okay, I agree. It is not like someone would use the debug information to reverse engineer our code lol.

**Pull request merged**
