### PR TITLE
Render refactor

### PR DESCRIPTION
**Pull request by thobbsinteractive**

### CODE REVIEW

**Comment by turican0** [comment]
Hi, how do you see the integration of this pull request?
I'm putting together a renderer merge now.

1)I'll wait until you integrate the Render refactor and then I'll redo the merge branch to merge.

2)Or I will integrate your changes into my branch and send as one pull together.

Thanks, Tom.

**Comment by thobbsinteractive** [comment]
Option 2 is probably the best.
But since I tagged you on the request, you can choose to approve and merge
it to Dev now if you want.

**Comment by thobbsinteractive** [comment]
That's okay. I am on holiday for a week from Sunday so I will not be able
to test and approve pull requests until the 10th. So take your time.

But if you have a moment to quickly fix the scoreboard before I go on
holiday I would really appreciate it. Or just tell me where and what to
fix. It is still crashing the game after the end of the level

**Comment by turican0** [comment]
Changes integrated in https://github.com/thobbsinteractive/magic-carpet-2-hd/pull/98

**Pull request closed without merging**
