### PR TITLE
Hotfix Linux multithreading

### PR DESCRIPTION
**Pull request by GrimSqueaker**
Use a custom config.ini on Linux in order to disable multithreaded rendering by default.
This makes the game run until we have a proper fix for multithreaded rendering.

### CODE REVIEW

**Review by thobbsinteractive — APPROVED** [review]

**Comment by GrimSqueaker** [comment]
@thobbsinteractive: For nostalgic reasons I chose the 4x3 aspect ratio. But in the end it does not matter. :-)

**Comment by thobbsinteractive** [comment]
Yeah, I realized that. I just got virtualbox running and am getting Ubuntu installed

**Comment by GrimSqueaker** [comment]
Great. Let me know, if you need help with anything.

**Comment by thobbsinteractive** [comment]
will do. I will finally be testing out the instructions

**Pull request merged**
