### PR TITLE
Cleanup unused code and started Linux regression tests

### PR DESCRIPTION
**Pull request by GrimSqueaker**
Removed some functions that are only needed for DOS memory handling, interrupts like 0x10, 0x31, 0x33.
Also started to fix some of the regression tests on Linux x64 and fixed some memory corruption because of memory allocated via `new[]` and freed via `delete` and not `delete[]`

### CODE REVIEW

**Comment by turican0** [comment]
Great, once the request is accepted, I'll reconcile it and accept the changes to my branch and then create a change request for the network. I want to move the network functions to engine/Network.cpp/.h so we can clean up sub_main.cpp a bit again.

**Comment by thobbsinteractive** [comment]
Nice work Seb. I will give this a test after work today. I have check most of the changes but am a little concerned about the changes to sub_main() hence my wanting to test it a bit.

**Comment by thobbsinteractive** [comment]
It tests okay, But @turican0 your review was requested, so I will leave approval to you.

**Review by turican0 — APPROVED** [review]
I approve all changes, I'll go through them in detail line by line when I put them in my branch, so if I come across a problem/inconsistency I'll detect it and work it into my pull request, Tom.

**Pull request merged**
